Rollczi/LiteCommands

- build.gradle
- litecommands-bukkit/build.gradle
- litecommands-bukkit/src/main/java/dev/rollczi/litecommands/bukkit/LiteBukkitCommand.java
- litecommands-bukkit/src/main/java/dev/rollczi/litecommands/bukkit/LiteBukkitCommandManager.java
- litecommands-bukkit/src/main/java/dev/rollczi/litecommands/bukkit/LiteBukkitFactory.java
- litecommands-bukkit/src/main/java/dev/rollczi/litecommands/bukkit/LiteBukkitPlatformManager.java
- litecommands-bukkit/src/main/java/dev/rollczi/litecommands/bukkit/LiteBukkitSender.java
- litecommands-core/src/main/java/dev/rollczi/litecommands/LiteCommands.java
- litecommands-core/src/main/java/dev/rollczi/litecommands/LiteCommandsBuilder.java
- litecommands-core/src/main/java/dev/rollczi/litecommands/LitePlatformManager.java
- litecommands-velocity/src/main/java/dev/rollczi/litecommands/velocity/LiteVelocityCommand.java
- litecommands-velocity/src/main/java/dev/rollczi/litecommands/velocity/LiteVelocityFactory.java
- litecommands-velocity/src/main/java/dev/rollczi/litecommands/velocity/LiteVelocityPlatformManager.java
- settings.gradle
https://github.com/Rollczi/LiteCommands/issues/4
> GH-4 Add bukkit support. 

- litecommands-core/src/main/java/dev/rollczi/litecommands/LiteCommandsBuilder.java
- litecommands-core/src/main/java/dev/rollczi/litecommands/annotations/parser/LiteAnnotationParser.java
> GH-6 Add placeholders support. (#21)

- litecommands-core/src/main/java/dev/rollczi/litecommands/LiteCommandsBuilder.java
- litecommands-core/src/test/java/dev/rollczi/litecommands/argument/TestCommand.java
(For example in toOptionHandler() method)
> GH-42 Fix warning bug when ArgumentHandler is created in Anonymous class. 

- litecommands-core/src/main/java/dev/rollczi/litecommands/LiteCommandsBuilder.java
- litecommands-core/src/main/java/dev/rollczi/litecommands/argument/ArgumentHandler.java
- litecommands-core/src/main/java/dev/rollczi/litecommands/component/LiteSection.java
- litecommands-core/src/test/java/dev/rollczi/litecommands/argument/DoubleArg.java
Log native class in warning.
Add @ArgumentName in DoubleArg class in test module. (Fix)
> GH-48 Add ArgumentHandler#isValid().

- litecommands-core/src/main/java/dev/rollczi/litecommands/LiteCommandsBuilder.java
- litecommands-core/src/main/java/dev/rollczi/litecommands/argument/ArgumentHandler.java
- litecommands-core/src/main/java/dev/rollczi/litecommands/argument/SingleArgumentHandler.java
- litecommands-core/src/main/java/dev/rollczi/litecommands/valid/messages/InvalidUseMessage.java
- litecommands-core/src/main/java/dev/rollczi/litecommands/valid/messages/LiteMessage.java
- litecommands-core/src/main/java/dev/rollczi/litecommands/valid/messages/PermissionMessage.java
- litecommands-core/src/main/java/dev/rollczi/litecommands/valid/messages/UseSchemeFormatting.java
- litecommands-core/src/test/java/dev/rollczi/litecommands/LiteTestExecutionResultHandler.java
- litecommands-core/src/test/java/dev/rollczi/litecommands/LiteTestPlatform.java
- litecommands-core/src/test/java/dev/rollczi/litecommands/argument/ArgumentCommandTest.kt
- litecommands-core/src/test/java/dev/rollczi/litecommands/joiner/JoinerCommandTest.kt
- litecommands-core/src/test/java/dev/rollczi/litecommands/scheme/SchemeUseCommandTest.kt
- litecommands-core/src/test/java/dev/rollczi/litecommands/scheme/TestSchemeMessage.java
- litecommands-core/src/test/java/dev/rollczi/litecommands/scheme/TestSchemeUseCommand.java
Improve use scheme generator API.
> GH-56 Add API methods to handle messages.

- README.md
- litecommands-minestom/README.md
Changes MineStom to Minestom in the main readme and changes Bungee to Minestom in the implementation specific readme
> GH-208 Fix README's for Minestom

- README.md
Update the list of projects using litecommands to include those with recent activity
> GH-228 Update the list of projects using litecommands.

- litecommands-annotations/test/dev/rollczi/litecommands/annotations/argument/resolver/standard/PeriodArgumentTest.java
- litecommands-core/src/dev/rollczi/litecommands/argument/resolver/standard/PeriodArgumentResolver.java
- litecommands-core/src/dev/rollczi/litecommands/time/PeriodParser.java
- litecommands-framework/src/dev/rollczi/litecommands/LiteCommandsFactory.java
> GH-222 Add PeriodArgumentResolver and corresponding tests, remove unused imports.

- README.md
- buildSrc/src/main/kotlin/litecommands-publish.gradle.kts
- examples/bukkit-adventure-platform/build.gradle.kts
- examples/bukkit-chatgpt/build.gradle.kts
- examples/bukkit/build.gradle.kts
- examples/velocity/build.gradle.kts
- litecommands-annotations/test/dev/rollczi/litecommands/annotations/route/RootCommandTest.java
- litecommands-core/src/dev/rollczi/litecommands/command/builder/CommandBuilderBase.java
- litecommands-core/src/dev/rollczi/litecommands/command/builder/CommandBuilderChildrenBase.java
- litecommands-core/src/dev/rollczi/litecommands/command/builder/CommandBuilderRootImpl.java
- litecommands-core/src/dev/rollczi/litecommands/input/raw/RawCommand.java
- litecommands-unit/src/dev/rollczi/litecommands/unit/TestPlatform.java
+ Cleanup TestPlatform. 
Resolve: #223
> GH-223 Fix root command children appender and add unit test related to this case. Release 3.0.0-BETA-pre23

- litecommands-annotations/test/dev/rollczi/litecommands/annotations/argument/resolver/standard/InstantArgumentTest.java
- litecommands-core/src/dev/rollczi/litecommands/argument/resolver/standard/InstantArgumentResolver.java
- litecommands-core/src/dev/rollczi/litecommands/input/raw/RawInput.java
- litecommands-core/src/dev/rollczi/litecommands/message/LiteMessages.java
- litecommands-framework/src/dev/rollczi/litecommands/LiteCommandsFactory.java
- litecommands-unit/src/dev/rollczi/litecommands/unit/AssertSuggest.java
> GH-233 Add Instant argument support

- README.md
- buildSrc/src/main/kotlin/litecommands-publish.gradle.kts
- examples/bukkit-adventure-platform/build.gradle.kts
- examples/bukkit-chatgpt/build.gradle.kts
- examples/bukkit/build.gradle.kts
- examples/velocity/build.gradle.kts
> GH-258 Release 3.0.0

- examples/bukkit/src/main/java/dev/rollczi/example/bukkit/ExamplePlugin.java
- examples/bukkit/src/main/java/dev/rollczi/example/bukkit/command/FlyCommand.java
- examples/bukkit/src/main/java/dev/rollczi/example/bukkit/validator/IsNotOp.java
- examples/bukkit/src/main/java/dev/rollczi/example/bukkit/validator/IsNotOpValidator.java
- litecommands-annotations/src/dev/rollczi/litecommands/annotations/validator/requirment/AnnotatedValidator.java
- litecommands-annotations/src/dev/rollczi/litecommands/annotations/validator/requirment/AnnotatedValidatorProcessor.java
- litecommands-annotations/src/dev/rollczi/litecommands/annotations/validator/requirment/RequirementAnnotatedValidatorImpl.java
- litecommands-annotations/test/dev/rollczi/litecommands/annotations/LiteTestSpec.java
- litecommands-annotations/test/dev/rollczi/litecommands/annotations/validator/requirment/AnnotatedValidatorTest.java
- litecommands-core/src/dev/rollczi/litecommands/argument/parser/ParseResult.java
- litecommands-core/src/dev/rollczi/litecommands/command/executor/CommandExecuteService.java
- litecommands-core/src/dev/rollczi/litecommands/context/ContextResult.java
- litecommands-core/src/dev/rollczi/litecommands/meta/Meta.java
- litecommands-core/src/dev/rollczi/litecommands/requirement/RequirementResult.java
- litecommands-core/src/dev/rollczi/litecommands/validator/ValidatorResult.java
- litecommands-core/src/dev/rollczi/litecommands/validator/requirment/RequirementValidator.java
- litecommands-framework/src/dev/rollczi/litecommands/extension/annotations/LiteAnnotationProcessExtension.java
- litecommands-framework/src/dev/rollczi/litecommands/extension/annotations/LiteAnnotationsProcessorExtension.java
> GH-263 Add API for requirements validators in command processing pipeline.

- README.md
- buildSrc/src/main/kotlin/litecommands-publish.gradle.kts
- examples/bukkit-adventure-platform/build.gradle.kts
- examples/bukkit-chatgpt/build.gradle.kts
- examples/bukkit/build.gradle.kts
- examples/velocity/build.gradle.kts
- litecommands-annotations/test/dev/rollczi/litecommands/annotations/wrapper/OptionalWrapperTest.java
- litecommands-core/src/dev/rollczi/litecommands/argument/resolver/standard/PeriodArgumentResolver.java
- litecommands-core/src/dev/rollczi/litecommands/command/executor/CommandExecuteService.java
- litecommands-core/src/dev/rollczi/litecommands/time/DurationParser.java
- litecommands-core/src/dev/rollczi/litecommands/time/PeriodParser.java
- litecommands-core/src/dev/rollczi/litecommands/time/TemporalAmountParser.java
> GH-267 Fix handling empty wrapper. Refactor time parsers in the argument resolver. Snapshot 3.0.2-SNAPSHOT

- README.md
- buildSrc/src/main/kotlin/litecommands-publish.gradle.kts
- examples/bukkit-adventure-platform/build.gradle.kts
- examples/bukkit-chatgpt/build.gradle.kts
- examples/bukkit/build.gradle.kts
- examples/velocity/build.gradle.kts
- litecommands-annotations/test/dev/rollczi/litecommands/annotations/suggestion/CustomSuggestionTest.java
- litecommands-core/src/dev/rollczi/litecommands/suggestion/SuggestionResult.java
- litecommands-core/src/dev/rollczi/litecommands/suggestion/SuggestionService.java
- litecommands-core/src/dev/rollczi/litecommands/util/StringUtil.java
> GH-253 Update suggestion service for case-insensitive matching. Release 3.0.2

- litecommands-annotations/test/dev/rollczi/litecommands/annotations/argument/resolver/standard/BigDecimalArgumentTest.java
- litecommands-annotations/test/dev/rollczi/litecommands/annotations/argument/resolver/standard/LocalDateTimeArgumentTest.java
- litecommands-core/src/dev/rollczi/litecommands/argument/resolver/standard/LocalDateTimeArgumentResolver.java
- litecommands-framework/src/dev/rollczi/litecommands/LiteCommandsFactory.java
> GH-271 Add LocalDateTime argument resolver.

- litecommands-jda/src/dev/rollczi/litecommands/jda/LiteJDAFactory.java
- litecommands-jda/src/dev/rollczi/litecommands/jda/MessageEmbedHandler.java
> GH-273 Add MessageEmbed result handler.

- examples/bukkit-adventure-platform/src/main/java/dev/rollczi/example/bukkit/adventure/ExampleAdventurePlugin.java
- examples/bukkit-chatgpt/src/main/java/dev/rollczi/example/bukkit/chatgpt/ExampleChatGptPlugin.java
- examples/bukkit/src/main/java/dev/rollczi/example/bukkit/ExamplePlugin.java
- examples/velocity/src/main/java/dev/rollczi/example/velocity/ExamplePlugin.java
- litecommands-adventure/src/dev/rollczi/litecommands/adventure/LiteAdventureExtension.java
- litecommands-annotations/benchmark/dev/rollczi/litecommands/benchmark/LiteBenchmark.java
- litecommands-annotations/src/dev/rollczi/litecommands/annotations/shortcut/Shortcut.java
- litecommands-annotations/test/dev/rollczi/litecommands/annotations/validator/requirment/AnnotatedValidatorTest.java
- litecommands-chatgpt/src/dev/rollczi/litecommands/chatgpt/LiteChatGptExtension.java
- litecommands-framework/src/dev/rollczi/litecommands/LiteCommandsBaseBuilder.java
- litecommands-framework/src/dev/rollczi/litecommands/LiteCommandsBuilder.java
- litecommands-framework/src/dev/rollczi/litecommands/configurator/LiteConfigurator.java
- litecommands-framework/src/dev/rollczi/litecommands/extension/LiteCommandsProviderExtension.java
- litecommands-framework/src/dev/rollczi/litecommands/extension/LiteExtension.java
- litecommands-framework/src/dev/rollczi/litecommands/extension/annotations/AnnotationsExtension.java
- litecommands-framework/src/dev/rollczi/litecommands/extension/annotations/LiteAnnotationsProcessorExtension.java
- litecommands-jda/src/dev/rollczi/litecommands/jda/LiteJDAFactory.java
- litecommands-minestom/test/dev/rollczi/litecommands/minestom/MineStomIntegrationSpec.java
- litecommands-programmatic/test/dev/rollczi/litecommands/programmatic/ProgrammaticApiTest.java
Use experimental builder methods in examples.
> GH-292 Add experimental api for annotations extension. 

- .github/README.md
> GH-312 Fix banner

- litecommands-annotations/src/dev/rollczi/litecommands/annotations/MethodCommandExecutor.java
- litecommands-annotations/src/dev/rollczi/litecommands/annotations/argument/Arg.java
- litecommands-annotations/src/dev/rollczi/litecommands/annotations/argument/ArgArgumentProcessor.java
- litecommands-annotations/test/dev/rollczi/litecommands/annotations/argument/NullableArgTest.java
- litecommands-annotations/test/dev/rollczi/litecommands/annotations/argument/OptionalArgTest.java
- litecommands-core/src/dev/rollczi/litecommands/argument/Argument.java
- litecommands-core/src/dev/rollczi/litecommands/argument/SimpleArgument.java
- litecommands-core/src/dev/rollczi/litecommands/argument/parser/ParseResult.java
- litecommands-core/src/dev/rollczi/litecommands/argument/parser/input/RawParseableInput.java
- litecommands-core/src/dev/rollczi/litecommands/command/executor/CommandExecuteService.java
- litecommands-core/src/dev/rollczi/litecommands/command/executor/LiteContext.java
- litecommands-core/src/dev/rollczi/litecommands/context/ContextResult.java
- litecommands-core/src/dev/rollczi/litecommands/flag/FlagArgument.java
- litecommands-core/src/dev/rollczi/litecommands/requirement/RequirementResult.java
- litecommands-core/src/dev/rollczi/litecommands/wrapper/ValueToWrap.java
- litecommands-core/src/dev/rollczi/litecommands/wrapper/Wrap.java
- litecommands-core/src/dev/rollczi/litecommands/wrapper/Wrapper.java
- litecommands-core/src/dev/rollczi/litecommands/wrapper/std/AbstractWrapper.java
- litecommands-core/src/dev/rollczi/litecommands/wrapper/std/CompletableFutureWrapper.java
- litecommands-core/src/dev/rollczi/litecommands/wrapper/std/OptionWrapper.java
- litecommands-core/src/dev/rollczi/litecommands/wrapper/std/OptionalWrapper.java
- litecommands-core/src/dev/rollczi/litecommands/wrapper/std/ValueWrapper.java
- litecommands-programmatic/src/dev/rollczi/litecommands/programmatic/LiteCommand.java
- litecommands-programmatic/test/dev/rollczi/litecommands/programmatic/NullableArgTest.java
Resolve https://github.com/Rollczi/LiteCommands/issues/305
> GH-305 Add nullable arguments

- litecommands-annotations/test/dev/rollczi/litecommands/annotations/schematic/SchematicTest.java
- litecommands-core/src/dev/rollczi/litecommands/command/CommandRouteImpl.java
- litecommands-core/src/dev/rollczi/litecommands/schematic/SchematicInput.java
- litecommands-core/src/dev/rollczi/litecommands/schematic/SimpleSchematicGenerator.java
- litecommands-core/test/dev/rollczi/litecommands/schematic/SchematicGeneratorTest.java
> GH-326 Display suggestions for route. Fix shortcuts schematics.

- litecommands-annotations/src/dev/rollczi/litecommands/annotations/InstanceSourceProcessor.java
- litecommands-annotations/src/dev/rollczi/litecommands/annotations/LiteCommandsAnnotations.java
- litecommands-annotations/src/dev/rollczi/litecommands/annotations/MethodCommandExecutor.java
- litecommands-annotations/src/dev/rollczi/litecommands/annotations/MethodInvoker.java
- litecommands-annotations/src/dev/rollczi/litecommands/annotations/validator/method/MethodValidator.java
- litecommands-annotations/src/dev/rollczi/litecommands/annotations/validator/method/MethodValidatorContext.java
- litecommands-annotations/src/dev/rollczi/litecommands/annotations/validator/method/MethodValidatorService.java
- litecommands-core/src/dev/rollczi/litecommands/handler/result/standard/CollectionHandler.java
- litecommands-framework/src/dev/rollczi/litecommands/LiteCommandsFactory.java
- litecommands-framework/src/dev/rollczi/litecommands/extension/annotations/AnnotationsExtension.java
- litecommands-framework/src/dev/rollczi/litecommands/extension/annotations/LiteAnnotationsProcessorExtension.java
- litecommands-jakarta/build.gradle.kts
- litecommands-jakarta/src/dev/rollczi/litecommands/jakarta/JakartaMethodValidator.java
- litecommands-jakarta/src/dev/rollczi/litecommands/jakarta/JakartaResult.java
- litecommands-jakarta/src/dev/rollczi/litecommands/jakarta/JakartaResultHandler.java
- litecommands-jakarta/src/dev/rollczi/litecommands/jakarta/JakartaSettings.java
- litecommands-jakarta/src/dev/rollczi/litecommands/jakarta/LiteJakartaExtension.java
- litecommands-jakarta/test/dev/rollczi/litecommands/jakarta/LiteJakartaExtensionTest.java
- settings.gradle.kts
> GH-332 Implement jakarta validation.

- litecommands-framework/src/dev/rollczi/litecommands/LiteCommandsBaseBuilder.java
> GH-306 Add copy constructor.

- examples/bukkit/src/main/java/dev/rollczi/example/bukkit/ExamplePlugin.java
- examples/bukkit/src/main/java/dev/rollczi/example/bukkit/command/NumberCommand.java
- litecommands-annotations/test/dev/rollczi/litecommands/annotations/argument/resolver/collector/ArrayArgumentTest.java
- litecommands-annotations/test/dev/rollczi/litecommands/annotations/argument/resolver/collector/ListArgumentTest.java
- litecommands-annotations/test/dev/rollczi/litecommands/annotations/argument/resolver/standard/NumberArgumentTest.java
- litecommands-annotations/test/dev/rollczi/litecommands/annotations/shortcut/ShortcutMultilevelTest.java
- litecommands-core/src/dev/rollczi/litecommands/argument/resolver/standard/NumberArgumentResolver.java
- litecommands-unit/src/dev/rollczi/litecommands/unit/AssertSuggest.java
> GH-348 Fix invalid number suggestions. Support decimal and negative number suggestions.

- litecommands-core/src/dev/rollczi/litecommands/join/JoinArgument.java
Resolve: https://github.com/Rollczi/LiteCommands/issues/379
> GH-379 Fix range exception in join argument

- litecommands-annotations/test/dev/rollczi/litecommands/annotations/permission/PermissionAnnotationSuggestionTest.java
- litecommands-annotations/test/dev/rollczi/litecommands/annotations/permission/PermissionAnnotationTest.java
- litecommands-core/src/dev/rollczi/litecommands/suggestion/SuggestionService.java
> GH-390 Fix suggestions permission validation for children of command.

- .github/TODO.md
- litecommands-annotations/src/dev/rollczi/litecommands/annotations/AnnotationProcessorService.java
- litecommands-annotations/src/dev/rollczi/litecommands/annotations/cooldown/Cooldown.java
- litecommands-annotations/src/dev/rollczi/litecommands/annotations/cooldown/CooldownAnnotationResolver.java
- litecommands-annotations/src/dev/rollczi/litecommands/annotations/validator/requirment/RequirementAnnotatedValidatorImpl.java
- litecommands-annotations/test/dev/rollczi/litecommands/annotations/cooldown/CooldownAnnotationTest.java
- litecommands-core/build.gradle.kts
- litecommands-core/src/dev/rollczi/litecommands/command/executor/CommandExecuteService.java
- litecommands-core/src/dev/rollczi/litecommands/cooldown/CooldownCompositeKey.java
- litecommands-core/src/dev/rollczi/litecommands/cooldown/CooldownContext.java
- litecommands-core/src/dev/rollczi/litecommands/cooldown/CooldownState.java
- litecommands-core/src/dev/rollczi/litecommands/cooldown/CooldownStateResultHandler.java
- litecommands-core/src/dev/rollczi/litecommands/cooldown/CooldownStateValidator.java
- litecommands-core/src/dev/rollczi/litecommands/message/LiteMessages.java
- litecommands-core/src/dev/rollczi/litecommands/meta/Meta.java
- litecommands-core/src/dev/rollczi/litecommands/scope/Scope.java
- litecommands-core/src/dev/rollczi/litecommands/validator/ValidatorService.java
- litecommands-core/src/dev/rollczi/litecommands/validator/requirement/RequirementValidator.java
- litecommands-framework/src/dev/rollczi/litecommands/LiteCommandsFactory.java
- litecommands-unit/src/dev/rollczi/litecommands/unit/AssertExecute.java
> GH-393 Add implementation for command cooldowns; Fix typo in requirement package name

- litecommands-annotations/test/dev/rollczi/litecommands/annotations/argument/resolver/standard/UUIDArgumentTest.java
- litecommands-core/src/dev/rollczi/litecommands/argument/resolver/standard/UUIDArgumentResolver.java
- litecommands-core/src/dev/rollczi/litecommands/message/LiteMessages.java
- litecommands-framework/src/dev/rollczi/litecommands/LiteCommandsFactory.java
It supports both with dashes and without dashes format
> GH-400 Add UUID argument resolver

- examples/bukkit/src/main/java/dev/rollczi/example/bukkit/ExamplePlugin.java
- examples/bukkit/src/main/java/dev/rollczi/example/bukkit/command/currency/CurrencyBalanceCommand.java
- examples/bukkit/src/main/java/dev/rollczi/example/bukkit/command/currency/CurrencyCommand.java
- examples/bukkit/src/main/java/dev/rollczi/example/bukkit/command/currency/CurrencyService.java
https://cdn.discordapp.com/attachments/896936981861392446/1252926988826443796/20240619-1001-25.6936416.mp4?ex=6673feb0&is=6672ad30&hm=9318d4dc25ce6f062e56e61cbfcbf7df041a94e9117151949b067412de437fbb&
> Add currency example with multi file command.

- examples/bukkit/src/main/java/dev/rollczi/example/bukkit/ExamplePlugin.java
- examples/bukkit/src/main/java/dev/rollczi/example/bukkit/command/currency/CurrencyBalanceCommand.java
- examples/bukkit/src/main/java/dev/rollczi/example/bukkit/command/currency/CurrencyCommand.java
- examples/bukkit/src/main/java/dev/rollczi/example/bukkit/command/currency/CurrencyService.java
https://cdn.discordapp.com/attachments/896936981861392446/1252926988826443796/20240619-1001-25.6936416.mp4?ex=6673feb0&is=6672ad30&hm=9318d4dc25ce6f062e56e61cbfcbf7df041a94e9117151949b067412de437fbb&
> GH-404 Add currency example with multi file command.

- litecommands-core/src/dev/rollczi/litecommands/argument/SimpleArgument.java
- litecommands-jda/src/dev/rollczi/litecommands/jda/JDACommandTranslator.java
> GH-425 Fix @OptionalArg annotation for the jda platform.

- litecommands-core/src/dev/rollczi/litecommands/shared/BiHashMap.java
> GH-442 Change default nativeMap of BiHashMap to ConcurrentHashMap

- litecommands-bukkit/src/dev/rollczi/litecommands/bukkit/argument/OfflinePlayerArgument.java
> GH-446 Hot fix offline player NPE.

- litecommands-annotations/src/dev/rollczi/litecommands/annotations/argument/KeyAnnotationResolver.java
- litecommands-annotations/src/dev/rollczi/litecommands/annotations/argument/profile/ProfileAnnotationProcessor.java
- litecommands-annotations/test/dev/rollczi/litecommands/annotations/async/AsyncArgumentsInitializeTest.java
- litecommands-chatgpt/src/dev/rollczi/litecommands/chatgpt/ChatGptArgument.java
- litecommands-core/src/dev/rollczi/litecommands/argument/Argument.java
- litecommands-core/src/dev/rollczi/litecommands/argument/MutableArgument.java
- litecommands-core/src/dev/rollczi/litecommands/argument/SimpleArgument.java
- litecommands-core/src/dev/rollczi/litecommands/argument/parser/ParserRegistry.java
- litecommands-core/src/dev/rollczi/litecommands/argument/parser/ParserRegistryImpl.java
- litecommands-core/src/dev/rollczi/litecommands/argument/profile/ArgumentProfileNamespace.java
- litecommands-core/src/dev/rollczi/litecommands/argument/resolver/collector/AbstractCollectorArgumentResolver.java
- litecommands-core/src/dev/rollczi/litecommands/argument/resolver/completeable/CompletableFutureResolver.java
- litecommands-core/src/dev/rollczi/litecommands/argument/resolver/optional/OptionalArgumentResolver.java
- litecommands-core/src/dev/rollczi/litecommands/argument/resolver/standard/TemporalAccessorArgumentResolver.java
- litecommands-core/src/dev/rollczi/litecommands/input/raw/RawCommand.java
- litecommands-core/src/dev/rollczi/litecommands/meta/Meta.java
- litecommands-core/src/dev/rollczi/litecommands/reflect/type/TypeToken.java
- litecommands-core/src/dev/rollczi/litecommands/requirement/ScheduledRequirementResolver.java
- litecommands-core/src/dev/rollczi/litecommands/schematic/SchematicFastGenerator.java
- litecommands-core/src/dev/rollczi/litecommands/schematic/SimpleSchematicGenerator.java
- litecommands-core/src/dev/rollczi/litecommands/shared/BiHashMap.java
- litecommands-core/test/dev/rollczi/litecommands/argument/resolver/completeable/CompletableFutureArgumentTest.java
- litecommands-unit/src/LiteBenchmark.java
- litecommands-unit/src/dev/rollczi/litecommands/unit/blocking/BlockingArgumentResolver.java
Resolve #444
Before:
```
Time: 983.1814ms, name: string
Time: 1108.091499ms, name: number
Time: 1438.9178ms, name: sub
Time: 1410.2626ms, name: sub optional
Time: 1284.739499ms, name: duration
```
After:
```
Time: 800.592099ms, name: string
Time: 895.206599ms, name: number
Time: 986.7691ms, name: sub
Time: 1032.193799ms, name: sub optional
Time: 1097.6033ms, name: duration
```
> GH-444 Improve parsers caches

- litecommands-jda/src/dev/rollczi/litecommands/jda/JDAPlatform.java
> GH-471 Fix jda number suggestions

- .github/workflows/publish.yml
- .github/workflows/sponsors.yml
Fix the fork repository constantly receiving email notifications of action failures
> GH-488 Update sponsors.yml

- examples/jda/build.gradle.kts
- examples/jda/src/main/java/dev/rollczi/example/jda/JDAExampleApplication.java
- examples/jda/src/main/java/dev/rollczi/example/jda/catboy/CatboyCommand.java
- examples/jda/src/main/java/dev/rollczi/example/jda/level/LevelCommand.java
- examples/jda/src/main/java/dev/rollczi/example/jda/level/LevelEntry.java
- examples/jda/src/main/java/dev/rollczi/example/jda/level/LevelService.java
- litecommands-jda/src/dev/rollczi/litecommands/jda/JDAPlatform.java
- litecommands-jda/src/dev/rollczi/litecommands/jda/LiteJDAFactory.java
- litecommands-jda/src/dev/rollczi/litecommands/jda/LiteJDASettings.java
- settings.gradle.kts
> GH-507 Support JDA fast guild commands registration and add example for the jda platform.

- litecommands-bungee/src/dev/rollczi/litecommands/bungee/LiteBungeeFactory.java
- litecommands-bungee/src/dev/rollczi/litecommands/bungee/LiteBungeeMessages.java
- litecommands-bungee/src/dev/rollczi/litecommands/bungee/argument/PlayerArgument.java
- litecommands-bungee/src/dev/rollczi/litecommands/bungee/argument/ServerInfoArgument.java
- litecommands-bungee/src/dev/rollczi/litecommands/bungee/context/PlayerOnlyContextProvider.java
- litecommands-bungee/src/dev/rollczi/litecommands/bungee/context/ServerContextProvider.java
- litecommands-bungee/src/dev/rollczi/litecommands/bungee/context/ServerInfoContextProvider.java
- litecommands-bungee/src/dev/rollczi/litecommands/bungee/tools/BungeeOnlyPlayerContextual.java
> GH-388: Improve BungeeCord support

- examples/bukkit-adventure-platform/src/main/java/dev/rollczi/example/bukkit/adventure/ExampleAdventurePlugin.java
- examples/bukkit-adventure-platform/src/main/java/dev/rollczi/example/bukkit/adventure/command/KeyCommand.java
- litecommands-adventure/build.gradle.kts
- litecommands-adventure/src/dev/rollczi/litecommands/adventure/AdventureKeyArgument.java
- litecommands-adventure/src/dev/rollczi/litecommands/adventure/LiteAdventureExtension.java
- litecommands-adventure/src/dev/rollczi/litecommands/adventure/LiteAdventureMessages.java
- litecommands-adventure/test/dev/rollczi/litecommands/adventure/AdventureKeyArgumentTest.java
- litecommands-annotations/test/dev/rollczi/litecommands/annotations/argument/resolver/collector/VarargsArgumentTest.kt
- litecommands-bukkit/src/dev/rollczi/litecommands/bukkit/BukkitScheduler.java
- litecommands-bukkit/src/dev/rollczi/litecommands/bukkit/Environment.java
- litecommands-bukkit/src/dev/rollczi/litecommands/bukkit/LiteBukkitFactory.java
- litecommands-bukkit/src/dev/rollczi/litecommands/bukkit/LiteBukkitMessages.java
- litecommands-bukkit/src/dev/rollczi/litecommands/bukkit/argument/NamespacedKeyArgument.java
- litecommands-core/src/dev/rollczi/litecommands/cooldown/CooldownStateResultHandler.java
- litecommands-core/src/dev/rollczi/litecommands/invalidusage/InvalidUsageHandlerImpl.java
- litecommands-core/src/dev/rollczi/litecommands/message/MessageRegistry.java
- litecommands-core/src/dev/rollczi/litecommands/permission/MissingPermissionResultHandler.java
- litecommands-core/test/dev/rollczi/litecommands/message/MessageRegistryTest.java
- litecommands-folia/src/dev/rollczi/litecommands/folia/FoliaExtension.java
- litecommands-jda/src/dev/rollczi/litecommands/jda/permission/DiscordMissingPermissionsHandler.java
- litecommands-unit/src/dev/rollczi/litecommands/unit/Arguments.java
This commit also supports Adventure variant of the NamespacedKey
> GH-561 Add adventure Key and bukkit NamespacedKey parsers and fix folia issues
